### PR TITLE
Python plugin fixes

### PR DESCRIPTION
**Pull request by nickolay**
I tried running dxr on itself with the python plugin <https://github.com/mozilla/dxr/pull/362> enabled. Some of these changes were needed to get it to run, and others I made while figuring out how it was supposed to work.

The detailed comments are in the individual commits.

### CODE REVIEW

**Comment by erikrose** [comment]
These look like great fixes. Taking a look now.

**Comment by erikrose** [comment]
Ha, know what it is? It's the info() ones. (Try `nosetests` in `python/tests/test_overrides`.) I bet if we lower them to debug()s, this whole issue goes away.

**Comment by erikrose** [comment]
Hmm, nope.

**Comment by erikrose** [comment]
(Btw, you're certainly correct that there's no "first" method in the FileToIndex contract. Thank you for reading the spec so closely; most people don't. :-))

I think I'm going to rebase out the logging commit for now, and if you want to figure out a way to keep debug()s quiet during tests, we can land them afterward. It would certainly be nice to be able to have them in there. Or, down the road, we could implement a more flexible status-indication system, one that plays more nicely with the multiprocess nature of plugins.

**Comment by nickolay** [comment]
Thanks for finishing this up for me, you're fantastic!

Re logging -- you were right. Nose sets debug logging, and the reason I didn't see it in test_imports was the difference between how `DxrInstanceTestCase` and `SingleFileTestCase` work:

https://github.com/mozilla/dxr/blob/a994140ce557e1147ef7c75d5d297543ab5fe6a8/dxr/testing.py#L169
vs
https://github.com/mozilla/dxr/blob/a994140ce557e1147ef7c75d5d297543ab5fe6a8/dxr/testing.py#L208

The former runs `dxr index` in a separate process, the output of which is swallowed. The latter runs in-process and prints debugging noise. Thanks for catching that! I agree that logging should not be added until this is dealt with.

**Comment by erikrose** [comment]
You're fantastic yourself! :-) It's always a treat to get such well-thought-through patches—and with tests to boot. And good sleuthing figuring out why test_imports is quiet.

Some background in case you're interested:

The behavior of DxrInstanceTestCase comes from a time when indexing was kicked off by a tree-specific makefile. Nowadays, we could easily change to an in-process model, but that actually makes things even worse for logging. Ideally, I suppose we'd have some kind of `multiprocessing` conduit back to the master process for logging—maybe put a logger-like object on TreeToIndex and/or FileToIndex that you could send messages to. At the moment, everything uses concurrent.futures, but that was really just for convenience and isn't the most efficient thing to do—we send large pickled objects repeatedly because of it—so I mean to eventually transition to lower-level constructs like Queues.

**Pull request closed without merging**
