### PR TITLE
fix bugzilla 1223442

### PR DESCRIPTION
**Pull request by jlmarr10824**
Replace glob with dict in phase 2 of condense.py csv file processing.

### CODE REVIEW

**Comment by erikrose** [comment]
Just curious—what kind of speed boost did you see from this?

**Comment by erikrose** [comment]
Looks like the tests didn't pass (poke around under "All checks have failed" above). Did they pass locally for you? If so, I'll just restart them.

**Comment by jlmarr10824** [comment]
Speed improved from days to hours.  Now able to do the indexing step in 7 hours with 4 workers.  Previously it would run for days before stalling.

Checks failing - I've tested in our environment - will look at the travis results.

**Comment by erikrose** [comment]
That's fantastic about the speed increase! You should have bragged about that more in your commit message. ;-)

**Comment by jlmarr10824** [comment]
I should have said I've tested our usage in our environment, but couldn't get the nosetests stuff working before making any changes so relied on our usage working.  Seems the test environment has changed a bit since the sqlite days.

**Comment by erikrose** [comment]
> Unless you restart and they pass I’ll revisit getting the unit test environment working in an unmodified master.

Doesn't look like the restart helped. :-( I'll leave it up to you whether it's easier to share your source into the docker environment or set up DXR in the environment that has your project's dependencies.

**Comment by erikrose** [comment]
Do you need a hand, @jlmarr10824?

**Comment by jlmarr10824** [comment]
This pull request has been superseded by #517.

**Pull request closed without merging**
