### PR TITLE
Fix bug 1178103, 404 on dir/ listings.

### PR DESCRIPTION
**Pull request by pelmers**
Quick fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1178103

### CODE REVIEW

**Comment by erikrose** [comment]
r+

**Comment by erikrose** [comment]
Actually, an even better solution would probably be to redirect to the slashless URL. That way, we'd be nicer to any caching we someday put in front.

**Comment by erikrose** [comment]
GitHub doesn't do the redirect. I'm surprised.

**Comment by erikrose** [comment]
What do you think?

**Comment by pelmers** [comment]
I think either way would work; the only things affected would be relative URL's, but we do not use them.

**Comment by erikrose** [comment]
At any rate, r+. It's better than it was, and we can always go the other way later.

**Comment by pelmers** [comment]
merged, not sure why github didn't pick it up automatically.

**Pull request closed without merging**
